version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    environment:
      - NEO4J_AUTH=neo4j/VeryStrongPassword2137!
      - NEO4J_server_directories_import=/import/gtfs
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j:/data
      - neo4j:/logs
      - neo4j:/import
      - neo4j:/plugins

volumes:
  neo4j:
