version: '3.8'

services:
  neo4j:
    image: neo4j:5.18
    container_name: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/test
      - NEO4J_PLUGINS='["apoc"]'
      - NEO4J_dbms_security_auth__enabled=true
    volumes:
      - neo4j_/data
      - ./config/neo4j/neo4j_import:/import
    restart: unless-stopped

  postgres:
    image: postgis/postgis:16-3.4
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: gtfs
      POSTGRES_USER: gtfs
      POSTGRES_PASSWORD: test
    volumes:
      - pg/var/lib/postgresql/data
      - ./config/postgres/pg_init:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  postgresql:
  neo4j:
